#!/usr/bin/env dash

total=0
while read -r input  || [ -n "$input" ]; do
    IFS=x
    set -- $input
    unset IFS
    l=$1; w=$2; h=$3
    min=$l; mid=$w; max=$h
    if [ "$min" -gt "$mid" ]; then
        tmp=$min; min=$mid; mid=$tmp
    fi
    if [ "$mid" -gt "$max" ]; then
        tmp=$mid; mid=$max; max=$tmp
    fi
    if [ "$min" -gt "$mid" ]; then
        tmp=$min; min=$mid; mid=$tmp
    fi
    ribbon=$(( 2 * $min + 2 * $mid + $l * $w * $h ))
    total=$(( $total + $ribbon ))
done
echo $total
